repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.4
  hooks:
    # Run the linter.
    - id: ruff
    - exclude: ^templates/  # This excludes any files inside the 'templates' directory at the root of the repository
    - id: ruff-format
    - exclude: ^templates/  # This excludes any files inside the 'templates' directory at the root of the repository